openapi: 3.0.3
info:
  title: Cart API
  description: API for managing a shopping cart.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /cart:
    get:
      summary: Get the current cart.
      responses:
        '200':
          description: The current cart.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /favourites:
    get:
      summary: Get favourite item IDs.
      responses:
        '200':
          description: A set of favourite item IDs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /cart/add-favourite:
    post:
      summary: Add an item to favourites.
      parameters:
        - name: itemId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Updated set of favourite item IDs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /cart/remove-favourite:
    delete:
      summary: Remove an item from favourites.
      parameters:
        - name: itemId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Updated set of favourite item IDs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /cart/update-item-quantity:
    post:
      summary: Update the quantity of an item in the cart.
      parameters:
        - name: itemId
          in: query
          required: true
          schema:
            type: string
        - name: quantity
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Updated cart.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /cart/add-item:
    post:
      summary: Add an item to a store in the cart.
      parameters:
        - name: storeId
          in: query
          required: true
          schema:
            type: string
        - name: itemId
          in: query
          required: true
          schema:
            type: string
        - name: itemName
          in: query
          required: true
          schema:
            type: string
        - name: imageUrl
          in: query
          required: true
          schema:
            type: string
        - name: baseItemPrice
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: quantity
          in: query
          required: true
          schema:
            type: integer
        - name: itemDiscountPercent
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Updated cart.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /cart/remove-item:
    delete:
      summary: Remove an item from the cart.
      parameters:
        - name: itemId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Updated cart.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /cart/clear:
    delete:
      summary: Clear the cart.
      responses:
        '200':
          description: Cleared cart.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /cart/add-store:
    post:
      summary: Add a store to the cart.
      parameters:
        - name: storeId
          in: query
          required: true
          schema:
            type: string
        - name: storeName
          in: query
          required: true
          schema:
            type: string
        - name: storeRating
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: storeReviewsCount
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Updated cart.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /cart/remove-store:
    delete:
      summary: Remove a store from the cart.
      parameters:
        - name: storeId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Updated cart.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
components:
  schemas:
    Cart:
      type: object
      properties:
        itemGroups:
          type: array
          items:
            $ref: '#/components/schemas/CartStoreItemsGroup'
    CartStoreItemsGroup:
      type: object
      properties:
        storeId:
          type: string
        storeName:
          type: string
        storeRating:
          type: number
          format: double
        storeReviewsCount:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    CartItem:
      type: object
      properties:
        id:
          type: string
        itemName:
          type: string
        imageUrl:
          type: string
        baseItemPrice:
          type: number
          format: double
        quantity:
          type: integer
        itemDiscountPercent:
          type: number
          format: double